# Generated by Django 5.2.8 on 2025-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('fecha_mantencion', models.DateField(blank=True, null=True, verbose_name='Venc. Mantención')),
                ('fecha_permiso', models.DateField(blank=True, null=True, verbose_name='Venc. Permiso Circulación')),
                ('kilometraje_actual', models.IntegerField(default=0, verbose_name='KM Actual')),
                ('kilometraje_maximo', models.IntegerField(default=0, verbose_name='KM Máximo (Mantención)')),
                ('km_diarios', models.FloatField(default=0.0, verbose_name='Promedio KM Diarios')),
                ('dias_uso_semanal', models.IntegerField(default=5, verbose_name='Días uso semana')),
            ],
        ),
    ]
