# Generated by Django 5.2.8 on 2025-12-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0002_vehiculo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AfpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "tasa",
                    models.FloatField(help_text="Porcentaje de descuento (Ej: 11.44)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsignacionFamiliarConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tramo", models.CharField(max_length=1)),
                ("ingreso_tope", models.IntegerField()),
                ("monto_por_carga", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracionGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=50, unique=True)),
                ("valor", models.FloatField()),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SaludConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "tasa",
                    models.FloatField(help_text="Porcentaje de descuento (Ej: 7.0)"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="depositodiario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="cargas_familiares",
            field=models.IntegerField(default=0, verbose_name="N° Cargas"),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="cargo",
            field=models.CharField(
                blank=True, default="Operario", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="fecha_ingreso",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="rut",
            field=models.CharField(
                max_length=12, null=True, unique=True, verbose_name="RUT"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="sueldo_base",
            field=models.IntegerField(default=460000, verbose_name="Sueldo Base"),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tiene_asignacion_familiar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="valor_hora_extra",
            field=models.IntegerField(default=0, verbose_name="Valor Hora Extra"),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="nombre",
            field=models.CharField(max_length=255, verbose_name="Nombre Completo"),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="afp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.afpconfig",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="salud",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.saludconfig",
            ),
        ),
        migrations.CreateModel(
            name="Remuneracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=7)),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("sueldo_liquido", models.IntegerField()),
                ("total_haberes", models.IntegerField()),
                ("total_descuentos", models.IntegerField()),
                (
                    "detalle_json",
                    models.JSONField(verbose_name="Detalle Completo JSON"),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.trabajador",
                    ),
                ),
            ],
            options={
                "ordering": ["-periodo"],
                "unique_together": {("trabajador", "periodo")},
            },
        ),
    ]
