# Generated by Django 5.2.8 on 2025-12-09 00:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0003_afpconfig_asignacionfamiliarconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RendicionDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                (
                    "credito_empresa",
                    models.BigIntegerField(default=0, verbose_name="Crédito Lipigas"),
                ),
                (
                    "prepago_vales",
                    models.BigIntegerField(default=0, verbose_name="Vales Prepago"),
                ),
                (
                    "transbank",
                    models.BigIntegerField(default=0, verbose_name="Transbank/Tarjeta"),
                ),
                (
                    "efectivo_entregado",
                    models.BigIntegerField(
                        default=0, verbose_name="Efectivo Entregado"
                    ),
                ),
                ("gas_5kg_cant", models.IntegerField(default=0)),
                ("gas_11kg_cant", models.IntegerField(default=0)),
                ("gas_45kg_cant", models.IntegerField(default=0)),
                ("cilindros_defectuosos", models.IntegerField(default=0)),
                (
                    "venta_esperada",
                    models.BigIntegerField(
                        default=0,
                        help_text="Monto total que el trabajador debía rendir (Venta * Precio)",
                    ),
                ),
                (
                    "balance_flujo",
                    models.BigIntegerField(
                        default=0, help_text="Diferencia: (Rendido - Esperado)"
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendición Diaria",
                "verbose_name_plural": "Rendiciones Diarias",
                "unique_together": {("trabajador", "fecha")},
            },
        ),
    ]
