# Generated by Django 5.2.8 on 2025-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rendiciondiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='bodega_asignada',
            field=models.CharField(choices=[('1221', '1221 (Manuel Peñafiel)'), ('1225', '1225 (David Perry)'), ('Ambos', 'Ambos')], default='Ambos', max_length=100),
        ),
    ]
