# Generated by Django 5.2.8 on 2025-12-17 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_trabajador_bodega_asignada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendiciondiaria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Rendición Diaria', 'verbose_name_plural': 'Rendiciones Diarias'},
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='balance_flujo',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='credito_empresa',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='gas_11kg_cant',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='gas_45kg_cant',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='gas_5kg_cant',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='prepago_vales',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='transbank',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='venta_esperada',
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='diferencia',
            field=models.BigIntegerField(default=0, help_text='Real - Esperado'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='efectivo_esperado',
            field=models.BigIntegerField(default=0, help_text='Venta - Descuentos'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='forklift_15kg',
            field=models.IntegerField(default=0, verbose_name='Forklift 15kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gas_11kg',
            field=models.IntegerField(default=0, verbose_name='Lipigas 11kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gas_15kg',
            field=models.IntegerField(default=0, verbose_name='Lipigas 15kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gas_45kg',
            field=models.IntegerField(default=0, verbose_name='Lipigas 45kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gas_5kg',
            field=models.IntegerField(default=0, verbose_name='Lipigas 5kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='horti_11kg',
            field=models.IntegerField(default=0, verbose_name='Horti 11kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='horti_15kg',
            field=models.IntegerField(default=0, verbose_name='Horti 15kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='horti_45kg',
            field=models.IntegerField(default=0, verbose_name='Horti 45kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='monto_credito',
            field=models.BigIntegerField(default=0, verbose_name='Crédito Empresa'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='monto_transbank',
            field=models.BigIntegerField(default=0, verbose_name='Transbank'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='monto_vales',
            field=models.BigIntegerField(default=0, verbose_name='Vales/Prepago'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='total_kilos',
            field=models.FloatField(default=0.0, help_text='Suma de Kilos Vendidos'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='total_venta',
            field=models.BigIntegerField(default=0, verbose_name='Total Venta (Guía)'),
        ),
        migrations.AlterField(
            model_name='rendiciondiaria',
            name='efectivo_entregado',
            field=models.BigIntegerField(default=0, verbose_name='Efectivo Real'),
        ),
    ]
