# Generated by Django 5.2.8 on 2025-12-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_rendiciondiaria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciondiaria',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='¿Rendición Cerrada?'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
