# Generated by Django 5.2.8 on 2025-12-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rendiciondiaria_cerrado_rendiciondiaria_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciondiaria',
            name='bodega',
            field=models.CharField(default='1221', max_length=10, verbose_name='Bodega del Turno'),
        ),
    ]
