# Generated by Django 5.2.8 on 2025-12-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rendiciondiaria_bodega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendiciondiaria',
            options={'ordering': ['-fecha', 'created_at'], 'verbose_name': 'Rendición Diaria', 'verbose_name_plural': 'Rendiciones Diarias'},
        ),
        migrations.AlterUniqueTogether(
            name='rendiciondiaria',
            unique_together=set(),
        ),
    ]
