# Generated by Django 5.2.8 on 2025-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_rendiciondiaria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='forklift_15kg',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='horti_11kg',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='horti_15kg',
        ),
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='horti_45kg',
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gas_ultra_15kg',
            field=models.IntegerField(default=0, verbose_name='Ultra 15kg'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gasc_15kg',
            field=models.IntegerField(default=0, verbose_name='Cat 15kg (15 Cat)'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gasc_5kg',
            field=models.IntegerField(default=0, verbose_name='Cat 5kg (05 Cat)'),
        ),
    ]
