# Generated by Django 5.2.8 on 2025-12-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_rendiciondiaria_forklift_15kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tarifa Estándar', max_length=100)),
                ('tarifa_5kg', models.IntegerField(default=0, verbose_name='Tarifa 5kg')),
                ('tarifa_11kg', models.IntegerField(default=0, verbose_name='Tarifa 11kg')),
                ('tarifa_15kg', models.IntegerField(default=0, verbose_name='Tarifa 15kg')),
                ('tarifa_45kg', models.IntegerField(default=0, verbose_name='Tarifa 45kg')),
                ('tarifa_cat_5kg', models.IntegerField(default=0, verbose_name='Tarifa Cat 5kg')),
                ('tarifa_cat_15kg', models.IntegerField(default=0, verbose_name='Tarifa Cat 15kg')),
                ('tarifa_ultra_15kg', models.IntegerField(default=0, verbose_name='Tarifa Ultra 15kg')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bodega', models.CharField(choices=[('1221', '1221 (Manuel Peñafiel)'), ('1225', '1225 (David Perry)'), ('Ambos', 'Ambos')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre Diario Global',
                'unique_together': {('fecha', 'bodega')},
            },
        ),
    ]
