# Generated by Django 5.2.8 on 2025-12-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_tarifacomision_cierrediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_extintor',
            field=models.DateField(blank=True, null=True, verbose_name='Venc. Extintor'),
        ),
    ]
