# Generated by Django 5.2.8 on 2025-12-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_vehiculo_fecha_extintor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciondiaria',
            name='comentario_gasto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle Gastos'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='gasto_total',
            field=models.IntegerField(default=0, verbose_name='Total Gastos'),
        ),
    ]
