# Generated by Django 5.2.8 on 2025-12-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_rendiciondiaria_comentario_gasto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendiciondiaria',
            name='comentario_gasto',
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='detalle_gastos',
            field=models.TextField(default='[]', verbose_name='JSON Detalle Gastos'),
        ),
    ]
