# Generated by Django 5.2.8 on 2026-01-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_remove_rendiciondiaria_comentario_gasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Trabaja Actualmente?'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='en_caja',
            field=models.BooleanField(default=False, verbose_name='¿Habilitado para Caja?'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo',
            field=models.CharField(choices=[('INTERNO', 'Interno (Contrato)'), ('EXTERNO', 'Externo (Fletero/Apoyo)')], default='INTERNO', max_length=20, verbose_name='Tipo Trabajador'),
        ),
    ]
