# Generated by Django 5.2.8 on 2026-01-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_trabajador_activo_trabajador_en_caja_trabajador_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='en_caja',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='filtro_trabajador',
            field=models.BooleanField(default=False, verbose_name='¿Habilitado en Filtros?'),
        ),
    ]
