# Generated by Django 5.2.8 on 2026-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_remove_trabajador_en_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='bodega_facturacion',
            field=models.CharField(blank=True, choices=[('1221', '1221 (Manuel Peñafiel)'), ('1225', '1225 (David Perry)')], max_length=10, null=True, verbose_name='Bodega de Facturación'),
        ),
    ]
