# Generated by Django 5.2.8 on 2026-01-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_trabajador_bodega_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuneracion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.trabajador'),
        ),
        migrations.AlterField(
            model_name='rendiciondiaria',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.trabajador', verbose_name='Trabajador'),
        ),
    ]
