# Generated by Django 5.2.8 on 2026-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_remuneracion_trabajador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracion',
            name='monto_faltante',
            field=models.IntegerField(default=0, verbose_name='Faltante Caja'),
        ),
        migrations.AddField(
            model_name='remuneracion',
            name='monto_impuesto',
            field=models.IntegerField(default=0, verbose_name='Impuesto Único'),
        ),
    ]
