# Generated by Django 5.2.8 on 2026-01-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remuneracion_monto_faltante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Plantilla Oficial', max_length=100)),
                ('archivo', models.FileField(upload_to='plantillas/remuneraciones/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
