# Generated by Django 5.2.8 on 2026-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_plantillaliquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracion',
            name='monto_anticipo',
            field=models.IntegerField(default=0, verbose_name='Anticipos del Mes'),
        ),
        migrations.AddField(
            model_name='rendiciondiaria',
            name='monto_anticipo',
            field=models.IntegerField(default=0, verbose_name='Anticipo'),
        ),
    ]
