# Generated by Django 5.2.8 on 2026-01-14 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_remuneracion_monto_anticipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemuneracionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('nro_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('pago_cilindros', models.IntegerField(default=0, verbose_name='Pago por Cilindros')),
                ('asistencia_tecnica', models.IntegerField(default=0, verbose_name='Asistencia Técnica')),
                ('subtotal_neto', models.IntegerField(default=0)),
                ('iva', models.IntegerField(default=0)),
                ('total_bruto', models.IntegerField(default=0)),
                ('prestamo', models.IntegerField(default=0)),
                ('anticipo', models.IntegerField(default=0)),
                ('faltante', models.IntegerField(default=0)),
                ('monto_total_pagar', models.IntegerField(default=0)),
                ('json_detalle_cilindros', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remuneraciones_externas', to='gestion.trabajador')),
            ],
            options={
                'verbose_name': 'Remuneración Externa',
                'unique_together': {('trabajador', 'mes', 'anio')},
            },
        ),
    ]
