# Generated by Django 5.2.8 on 2026-01-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_remuneracionexterna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuneracionexterna',
            name='anticipo',
        ),
        migrations.RemoveField(
            model_name='remuneracionexterna',
            name='faltante',
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='anticipo_base',
            field=models.IntegerField(default=0, verbose_name='Anticipo DB (Rendiciones)'),
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='anticipo_extra',
            field=models.IntegerField(default=0, verbose_name='Anticipo Manual Extra'),
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='faltante_base',
            field=models.IntegerField(default=0, verbose_name='Faltante DB (Rendiciones)'),
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='faltante_extra',
            field=models.IntegerField(default=0, verbose_name='Faltante Manual Extra'),
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='json_otros_descuentos',
            field=models.TextField(default='[]', verbose_name='JSON Lista Descuentos'),
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='total_descuentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remuneracionexterna',
            name='total_otros_descuentos',
            field=models.IntegerField(default=0),
        ),
    ]
