# Generated by Django 5.2.8 on 2026-01-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_remove_remuneracionexterna_anticipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuneracionexterna',
            name='prestamo',
        ),
    ]
