# Generated by Django 5.2.8 on 2026-01-18 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_remove_remuneracionexterna_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_reporte_km',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del Reporte KM'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.IntegerField(default=0, verbose_name='Último KM Reportado (Base)'),
        ),
    ]
