# Generated by Django 5.2.8 on 2026-01-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_vehiculo_fecha_reporte_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Razón Social / Nombre')),
                ('apodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apodo / Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, verbose_name='N° Factura')),
                ('valor', models.IntegerField(verbose_name='Monto Total')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('imagen_factura', models.ImageField(upload_to='facturas_credito/', verbose_name='Foto Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='gestion.clientecredito')),
                ('fletero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.trabajador', verbose_name='Fletero Responsable')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
