# Generated by Django 5.2.8 on 2026-01-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_clientecredito_facturacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacredito',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Pagado?'),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='imagen_factura',
            field=models.ImageField(blank=True, null=True, upload_to='facturas_credito/', verbose_name='Foto Factura'),
        ),
    ]
