# Generated by Django 5.2.8 on 2026-01-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_facturacredito_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacredito',
            name='fletero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.trabajador', verbose_name='Fletero Responsable'),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Factura'),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='valor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto Total'),
        ),
    ]
