# Generated by Django 5.2.8 on 2026-01-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_alter_facturacredito_fletero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacredito',
            name='fecha_real_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Real de Pago'),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha Emisión'),
        ),
    ]
