# Generated by Django 5.2.8 on 2026-01-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_facturacredito_fecha_real_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacredito',
            name='nota_pago',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de Pago'),
        ),
    ]
