# Generated by Django 5.2.8 on 2026-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_facturacredito_nota_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacredito',
            name='imagen_factura',
        ),
    ]
