# Generated by Django 5.2.8 on 2026-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_remove_facturacredito_imagen_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacredito',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='facturacredito',
            name='recepcionista',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Recibido por'),
        ),
    ]
