# Generated by Django 5.2.8 on 2025-11-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Completo')),
                ('bodega_asignada', models.CharField(choices=[('Manuel Peñafiel', '1221 (Manuel Peñafiel)'), ('David Perry', '1225 (David Perry)'), ('Ambos', 'Ambos')], default='Ambos', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepositoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bodega_nombre', models.CharField(choices=[('Manuel Peñafiel', '1221 (Manuel Peñafiel)'), ('David Perry', '1225 (David Perry)')], max_length=100)),
                ('numero_lote', models.IntegerField(default=1)),
                ('nombre_lote', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre de Lote (Opcional)')),
                ('total_aportes', models.BigIntegerField(default=0)),
                ('total_desglose', models.BigIntegerField(default=0, verbose_name='Total Desglose (Efectivo)')),
                ('diferencia', models.BigIntegerField(default=0)),
                ('total_cheques', models.BigIntegerField(default=0)),
                ('cerrado', models.BooleanField(default=False, verbose_name='¿Lote Cerrado?')),
            ],
            options={
                'unique_together': {('fecha', 'bodega_nombre', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='DepositoDesglose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=50)),
                ('valor_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField(default=0)),
                ('total_denominacion', models.BigIntegerField(default=0)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose', to='depositos.depositodiario')),
            ],
        ),
        migrations.CreateModel(
            name='DepositoAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.BigIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='depositos.depositodiario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depositos.trabajador', verbose_name='Trabajador')),
            ],
        ),
    ]
